version: "3.7"

services:
  calfit-mysql:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "calfit"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
      - "./calfit-mysql:/var/lib/mysql"
    restart: always
  calfit-backend:
    image: "calfit-backend:1.0.0"
    ports:
      - "8080:8080"
    depends_on:
      - "calfit-mysql"
    volumes:
      - "./calfit-backend:/var/www/html"
    restart: always
