// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sessions "CalFit/business/sessions"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int) (sessions.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 sessions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) sessions.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sessions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]sessions.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []sessions.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []sessions.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sessions.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *Repository) GetById(ctx context.Context, id int) (sessions.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 sessions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) sessions.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sessions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, _a1
func (_m *Repository) Insert(ctx context.Context, _a1 sessions.Domain) (sessions.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 sessions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, sessions.Domain) sessions.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(sessions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sessions.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Repository) Update(ctx context.Context, _a1 sessions.Domain) (sessions.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 sessions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, sessions.Domain) sessions.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(sessions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sessions.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
