// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	superadmins "CalFit/business/superadmins"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) ([]superadmins.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []superadmins.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []superadmins.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]superadmins.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *Repository) GetByUsername(ctx context.Context, username string) (superadmins.Domain, error) {
	ret := _m.Called(ctx, username)

	var r0 superadmins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) superadmins.Domain); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(superadmins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, _a1
func (_m *Repository) Login(ctx context.Context, _a1 superadmins.Domain) (superadmins.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 superadmins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, superadmins.Domain) superadmins.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(superadmins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, superadmins.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, _a1
func (_m *Repository) Register(ctx context.Context, _a1 superadmins.Domain) (superadmins.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 superadmins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, superadmins.Domain) superadmins.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(superadmins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, superadmins.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword provides a mock function with given fields: ctx, _a1
func (_m *Repository) UpdatePassword(ctx context.Context, _a1 superadmins.Domain) (superadmins.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 superadmins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, superadmins.Domain) superadmins.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(superadmins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, superadmins.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
