// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	classes "CalFit/business/classes"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DomainRepository is an autogenerated mock type for the DomainRepository type
type DomainRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, domain
func (_m *DomainRepository) Create(ctx context.Context, domain classes.Domain) (classes.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 classes.Domain
	if rf, ok := ret.Get(0).(func(context.Context, classes.Domain) classes.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(classes.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, classes.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *DomainRepository) GetAll(ctx context.Context) ([]classes.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []classes.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []classes.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]classes.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *DomainRepository) GetById(ctx context.Context, id string) (classes.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 classes.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) classes.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(classes.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
